name: structure pipeline
run-name: Basic Strutures 🚀
on: [push]
jobs:
  norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: install python dependecies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install norminette
    - name: Norminette
      run: norminette
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build project
      run: make -C philo
  valgrind:
    name: Valgrind
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Install valgrind
      run: sudo apt install valgrind -y
    - name: Build project
      run: make -C philo
    - name: Exec binary with valgrind
      run: valgrind philo/philo 3 3 3 3
      